apiVersion: dal.io/v1alpha1
kind: Projection
metadata:
  name: events-combined
spec:
  sources:
    - connectionRef: postgres
      routing:
        type: timeRange
        timestampColumn: occurred_at
        maxAge: 7d
      view:
        table: user_events
        columns:
          - source: event_id
          - source: user_id
          - source: event_type
          - source: occurred_at
    - connectionRef: datalake
      routing:
        type: timeRange
        timestampColumn: occurred_at
        minAge: 7d
      view:
        table: events/raw
        columns:
          - source: event_id
          - source: user_id
          - source: event_type
          - source: occurred_at
