apiVersion: dal.io/v1alpha1
kind: Projection
metadata:
  name: events-history
spec:
  sources:
    - connectionRef: datalake
      view:
        table: events/raw
        columns:
          - source: event_id
          - source: user_id
          - source: event_type
          - source: occurred_at
